layout_spectrum: 0.146356
typography_spectrum: 0.5274791
color:
  saturation: 0.7030681
  lightness: 0.978236
  brandStrength: 0.6800276
  rhythmicContrast: 0.4274921
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Interiors Warehouse
